---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --tag thayspm 
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v3
      - run: docker build . --tag thayspm
      - run: docker run -d -p 3000:3000 thayspm
      - uses: AppThreat/sast-scan-action@master
        with:
         type: nodejs
  deploy-job:
    needs: [build-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --tag thays90/aplicacao_web 
      - run: docker login --username thays90 --password ${{ secrets.DOCKER_PASS }}
      - run: docker push thays90/aplicacao_web
